!INTERFILE  :=
name of data file := EmSin_n_norm.yaff
originating system := ECAT 962
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := BIGENDIAN
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {None}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 5
matrix axis label [3] := view
!matrix size [3] := 144
matrix axis label [2] := axial coordinate
!matrix size [2] := { 63,53,53,35,35}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 288
minimum ring difference per segment := { -4,-13,5,-22,14}
maximum ring difference per segment := { 4,-5,13,-14,22}
Scanner parameters:= 
Scanner type := RATPET
Number of rings                          := 32
Number of detectors per ring             := 576
Inner ring diameter (cm)                 := 82.4
Average depth of interaction (cm)        := 0.7
Distance between rings (cm)              := 0.485
Default bin size (cm)                    := 0.225
View offset (degrees)                    := 0
Maximum number of non-arc-corrected bins := 288
Default number of arc-corrected bins     := 288
Number of blocks per bucket in transaxial direction         := 3
Number of blocks per bucket in axial direction              := 4
Number of crystals per block in axial direction             := 8
Number of crystals per block in transaxial direction        := 8
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 8
Number of crystals per singles unit in transaxial direction := 24
end scanner parameters:=
effective central bin size (cm) := 0.228528
image scaling factor[1] := 1
data offset in bytes[1] := 0
number of time frames := 1
!END OF INTERFILE :=
